package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Avion generated by hbm2java
 */
@Entity
@Table(name="avion"
    ,schema="public"
)
public class Avion  implements java.io.Serializable {


     private int idAvion;
     private String modelo;
     private BigDecimal capacidad;
     private String fabricante;
     private Set vuelos = new HashSet(0);

    public Avion() {
    }

	
    public Avion(int idAvion, String modelo, BigDecimal capacidad, String fabricante) {
        this.idAvion = idAvion;
        this.modelo = modelo;
        this.capacidad = capacidad;
        this.fabricante = fabricante;
    }
    public Avion(int idAvion, String modelo, BigDecimal capacidad, String fabricante, Set vuelos) {
       this.idAvion = idAvion;
       this.modelo = modelo;
       this.capacidad = capacidad;
       this.fabricante = fabricante;
       this.vuelos = vuelos;
    }
   
     @Id 

    
    @Column(name="id_avion", unique=true, nullable=false)
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    
    @Column(name="modelo", nullable=false, length=50)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="capacidad", nullable=false, precision=131089, scale=0)
    public BigDecimal getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(BigDecimal capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="fabricante", nullable=false, length=50)
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="avion")
    public Set getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set vuelos) {
        this.vuelos = vuelos;
    }




}


