package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,schema="public"
)
public class Departments  implements java.io.Serializable {


     private short departmentId;
     private String departmentName;
     private Integer managerId;
     private Short locationId;
     private Set employeeses = new HashSet(0);

    public Departments() {
    }

	
    public Departments(short departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }
    public Departments(short departmentId, String departmentName, Integer managerId, Short locationId, Set employeeses) {
       this.departmentId = departmentId;
       this.departmentName = departmentName;
       this.managerId = managerId;
       this.locationId = locationId;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="department_id", unique=true, nullable=false, precision=4, scale=0)
    public short getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(short departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="department_name", nullable=false, length=30)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="manager_id", precision=6, scale=0)
    public Integer getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    
    @Column(name="location_id", precision=4, scale=0)
    public Short getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Short locationId) {
        this.locationId = locationId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


