package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pasajero generated by hbm2java
 */
@Entity
@Table(name="pasajero"
    ,schema="public"
)
public class Pasajero  implements java.io.Serializable {


     private int idPasajero;
     private BigDecimal identificacion;
     private char tipoIdentificacion;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private char sexo;
     private BigDecimal celular;
     private String direccion;
     private Date fechaNacimiento;
     private Set reservas = new HashSet(0);

    public Pasajero() {
    }

	
    public Pasajero(int idPasajero, BigDecimal identificacion, char tipoIdentificacion, String primerNombre, String primerApellido, char sexo, BigDecimal celular, String direccion, Date fechaNacimiento) {
        this.idPasajero = idPasajero;
        this.identificacion = identificacion;
        this.tipoIdentificacion = tipoIdentificacion;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.sexo = sexo;
        this.celular = celular;
        this.direccion = direccion;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Pasajero(int idPasajero, BigDecimal identificacion, char tipoIdentificacion, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, char sexo, BigDecimal celular, String direccion, Date fechaNacimiento, Set reservas) {
       this.idPasajero = idPasajero;
       this.identificacion = identificacion;
       this.tipoIdentificacion = tipoIdentificacion;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.sexo = sexo;
       this.celular = celular;
       this.direccion = direccion;
       this.fechaNacimiento = fechaNacimiento;
       this.reservas = reservas;
    }
   
     @Id 

    
    @Column(name="id_pasajero", unique=true, nullable=false)
    public int getIdPasajero() {
        return this.idPasajero;
    }
    
    public void setIdPasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }

    
    @Column(name="identificacion", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(BigDecimal identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="tipo_identificacion", nullable=false, length=1)
    public char getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(char tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    
    @Column(name="primer_nombre", nullable=false, length=50)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="segundo_nombre", length=50)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="primer_apellido", nullable=false, length=50)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="segundo_apellido", length=50)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    
    @Column(name="sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="celular", nullable=false, precision=131089, scale=0)
    public BigDecimal getCelular() {
        return this.celular;
    }
    
    public void setCelular(BigDecimal celular) {
        this.celular = celular;
    }

    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=13)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


