package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name="reserva"
    ,schema="public"
)
public class Reserva  implements java.io.Serializable {


     private int idReserva;
     private Pasajero pasajero;
     private Vuelo vuelo;
     private Date fechaCreacion;
     private char estado;

    public Reserva() {
    }

    public Reserva(int idReserva, Pasajero pasajero, Vuelo vuelo, Date fechaCreacion, char estado) {
       this.idReserva = idReserva;
       this.pasajero = pasajero;
       this.vuelo = vuelo;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id_reserva", unique=true, nullable=false)
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pasajero", nullable=false)
    public Pasajero getPasajero() {
        return this.pasajero;
    }
    
    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vuelo", nullable=false)
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=13)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


