package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name="ruta"
    ,schema="public"
)
public class Ruta  implements java.io.Serializable {


     private int idRuta;
     private String aeropuertoOrigen;
     private String aeropuertoDestino;
     private Date duracion;
     private Set vuelos = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(int idRuta, String aeropuertoOrigen, String aeropuertoDestino) {
        this.idRuta = idRuta;
        this.aeropuertoOrigen = aeropuertoOrigen;
        this.aeropuertoDestino = aeropuertoDestino;
    }
    public Ruta(int idRuta, String aeropuertoOrigen, String aeropuertoDestino, Date duracion, Set vuelos) {
       this.idRuta = idRuta;
       this.aeropuertoOrigen = aeropuertoOrigen;
       this.aeropuertoDestino = aeropuertoDestino;
       this.duracion = duracion;
       this.vuelos = vuelos;
    }
   
     @Id 

    
    @Column(name="id_ruta", unique=true, nullable=false)
    public int getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }

    
    @Column(name="aeropuerto_origen", nullable=false, length=100)
    public String getAeropuertoOrigen() {
        return this.aeropuertoOrigen;
    }
    
    public void setAeropuertoOrigen(String aeropuertoOrigen) {
        this.aeropuertoOrigen = aeropuertoOrigen;
    }

    
    @Column(name="aeropuerto_destino", nullable=false, length=100)
    public String getAeropuertoDestino() {
        return this.aeropuertoDestino;
    }
    
    public void setAeropuertoDestino(String aeropuertoDestino) {
        this.aeropuertoDestino = aeropuertoDestino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="duracion", length=29)
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ruta")
    public Set getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set vuelos) {
        this.vuelos = vuelos;
    }




}


