package entities;
// Generated 05-oct-2016 21:39:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,schema="public"
)
public class Vuelo  implements java.io.Serializable {


     private int idVuelo;
     private Avion avion;
     private Ruta ruta;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private Set reservas = new HashSet(0);

    public Vuelo() {
    }

	
    public Vuelo(int idVuelo, Avion avion, Ruta ruta, Date fecha, Date horaInicio, Date horaFin) {
        this.idVuelo = idVuelo;
        this.avion = avion;
        this.ruta = ruta;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
    }
    public Vuelo(int idVuelo, Avion avion, Ruta ruta, Date fecha, Date horaInicio, Date horaFin, Set reservas) {
       this.idVuelo = idVuelo;
       this.avion = avion;
       this.ruta = ruta;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.reservas = reservas;
    }
   
     @Id 

    
    @Column(name="id_vuelo", unique=true, nullable=false)
    public int getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(int idVuelo) {
        this.idVuelo = idVuelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_avion", nullable=false)
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ruta", nullable=false)
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hora_inicio", nullable=false, length=29)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hora_fin", nullable=false, length=29)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vuelo")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


